config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions", passwords: "admins/passwords", registrations: "admins/registrations"}
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations"}

  resources :workout_programs

  authenticated :user do
    root to: 'users#show', as: :authenticated_user_root
  end

  authenticated :admin do
    root to: 'admins#index', as: :authenticated_admin_root
  end

  unauthenticated do
    root to: 'home#index'
  end

  resources :users do
    resources :profile, only: [:index, :show, :new, :create, :update, :edit]
    collection {get :workout_program}
  end

  namespace :admins do
    resources :users, only: [:index, :new, :create, :update, :edit]
    resources :profile, only: [:index, :new, :create, :update, :edit]
  end

  resources :admins do [:index]
    collection {get :import}
  end

  resources :sports do
    collection {post :import}
  end
  
  resources :home, only: [:index] do
    collection {get :import}
    collection {get :contact}
    collection {get :terms}
    collection {get :team}
  end

  resources :sport_roles, only: [:index] do
    collection {post :import}
  end

  resources :qualities, only: [:index] do
    collection {post :import}
  end

  resources :capacities, only: [:index] do
    collection {post :import}
  end

  resources :muscular_groups, only: [:index] do
    collection {post :import}
  end

  resources :training_methods, only: [:index] do
    collection {post :import}
  end

  resources :exercises, only: [:index] do
    collection {post :import}
  end

  resources :intensities, only: [:index] do
    collection {post :import}
  end

  resources :levels, only: [:index] do
    collection {post :import}
  end

  resources :extypes, only: [:index] do
    collection {post :import}
  end

  resources :muscles, only: [:index] do
    collection {post :import}
  end

  resources :variants, only: [:index] do
    collection {post :import}
  end

  resources :roles_muscular_group_capacities, only: [:index] do
    collection {post :import}
  end

  resources :training_method_exercises, only: [:index] do
    collection {post :import}
  end

  resources :training_method_levels, only: [:index] do
    collection {post :import}
  end

  resources :training_method_intensities, only: [:index] do
    collection {post :import}
  end

  resources :exercise_variants, only: [:index] do
    collection {post :import}
  end

  resources :charges do
    collection {get :success}
    collection {get :new_card}
    collection {post :create_card}
    collection {post :delete_card}
    collection {post :subscribe}
    collection {post :cancel_subscription}
  end

end

app/views/admins/create.html.erb
<h1>Admins#create</h1>
<p>Find me in app/views/admins/create.html.erb</p>

app/views/admins/destroy.html.erb
<h1>Admins#destroy</h1>
<p>Find me in app/views/admins/destroy.html.erb</p>

app/views/admins/edit.html.erb
<h1>Admins#edit</h1>
<p>Find me in app/views/admins/edit.html.erb</p>

app/views/admins/import.html.erb
<h1 class="hidden">
  <%= title 'Importer' %>
</h1>
<section>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Table</th>
        <th scope="col">File path</th>
        <th scope="col">Import File</th>
        <th scope="col">Import checking</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td>Sport</td>
        <td>
            <%= form_tag import_sports_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>
        <td>
            <%if !@sports.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
      <tr>
        <th scope="row">2</th>
        <td>Sport Roles</td>
        <td>
            <%= form_tag import_sport_roles_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>
        <td>
            <%if !@sportrole.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td>Qualities</td>
        <td>
            <%= form_tag import_qualities_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>
        <td>
            <%if !@quality.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
      <tr>
        <th scope="row">4</th>
        <td>Capacities</td>
        <td>
            <%= form_tag import_capacities_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>
        <td>
            <%if !@capacity.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
      <tr>
        <th scope="row">5</th>
        <td>Muscular Groups</td>
        <td>
            <%= form_tag import_muscular_groups_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>
        <td>
            <%if !@muscular_group.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
      <tr>
        <th scope="row">6</th>
        <td>Training Methods</td>
        <td>
            <%= form_tag import_training_methods_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>
        <td>
            <%if !@training_method.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
      <tr>
        <th scope="row">7</th>
        <td>Training Exercises</td>
        <td>
            <%= form_tag import_exercises_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>
        <td>
            <%if !@exercises.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
      <tr>
        <th scope="row">8</th>
        <td>Intensity</td>
        <td>
            <%= form_tag import_intensities_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>
        <td>
            <%if !@intensities.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
      <tr>
        <th scope="row">9</th>
        <td>Levels</td>
        <td>
            <%= form_tag import_levels_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>
        <td>
            <%if !@levels.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
      <tr>
        <th scope="row">10</th>
        <td>Exercises types</td>
        <td>
            <%= form_tag import_extypes_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>
        <td>
            <%if !@extypes.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
      <tr>
        <th scope="row">11</th>
        <td>Muscles</td>
        <td>
            <%= form_tag import_muscles_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>
        <td>
            <%if !@muscles.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
      <tr>
        <th scope="row">12</th>
        <td>Variants</td>
        <td>
            <%= form_tag import_variants_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>
        <td>
            <%if !@variants.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
      <tr>
        <th scope="row">13</th>
        <td>JT Roles MG Capacities</td>
        <td>
            <%= form_tag import_roles_muscular_group_capacities_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>
        <td>
            <%if !@roles.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
      <tr>
        <th scope="row">14</th>
        <td>JT Methods Exercises</td>
        <td>
            <%= form_tag import_training_method_exercises_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>      
        <td>
            <%if !@methodexercises.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
      <tr>
        <th scope="row">15</th>
        <td>JT Methods Levels</td>
        <td>
            <%= form_tag import_training_method_levels_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>      
        <td>
            <%if !@methodlevels.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
      <tr>
        <th scope="row">16</th>
        <td>JT Methods Intensities</td>
        <td>
            <%= form_tag import_training_method_intensities_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>      
        <td>
            <%if !@methodintensities.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
      <tr>
        <th scope="row">17</th>
        <td>JT Exercise Variant Muscle</td>
        <td>
            <%= form_tag import_exercise_variants_path, multipart: true do%>
              <%= file_field_tag :file%> 
        </td>
        <td>
            <%= submit_tag "Import from file"%>
            <%end%>
        </td>      
        <td>
            <%if !@exercisevariants.empty?%>
            <i class="fas fa-check"></i>
            <%else%>
            <i class="fas fa-times-circle"></i>
            <%end%>
        </td>
      </tr>
    </tbody>
  </table>

  <%= link_to "Retour", root_path, class:"btn btn-outline-dark btn-block mt-3" %>            

</section>

app/views/admins/index.html.erb
<%= render "layouts/jumbotron" %>
<div class="container mt-4">

  <div class="card-deck">

    <div class="card">
      <div class="d3">
        <h5 class="titled3">Compteur</h5>
      </div>
      <div class="card-body text-center">
                <h1 class="card-title text-center"><%=@users.count%></h1>
                <p>Nombres d'inscrits</p>
                <h1 class="card-title text-center">
                <%if @count_sub == nil %>
                0
                <%else%>
                <%=@count_sub%>
                <%end%></h1>
                <p>Nombres d'abonnés</p>
      </div>
      <div class="card-footer text-center">
      <%= link_to "Voir les utilisateurs", admins_users_path, class:"btn btn-warning btn-sm"%>

      </div>
    </div>

    <div class="card text-center">
      <div class="d3">
      <h5 class="titled3">Base de données</h5>
      </div>
      <div class="card-body">
          <h1 class="card-title text-center"><%=@numb%></h1>
          <p>Nombres de tables de BDD</p>
      </div>
      <div class="card-footer">
      <%= link_to "Import CSV", import_admins_path, class:"btn btn-warning btn-sm"%>
      </div>
    </div>

    <div class="card text-center">
      <div class="d3">
      <h5 class="titled3">Administrateurs</h5>
      </div>
      <div class="card-body">
          <h1 class="card-title text-center"><%=@admins.count%></h1>
          <p>Nombres d'admins</p>
      </div>
      <div class="card-footer">
      <%= link_to "Créer un admin", new_admin_path, class:"btn btn-warning btn-sm"%>
      </div>
    </div>
  
  </div>

</div>

app/views/admins/new.html.erb
<%= render "layouts/jumbotron" %>
<div class="container mt-4">

<h1 class="hidden">
<%= title 'Ajouter Admin' %>
</h1>

<div class="row d-flex flex-column justify-content-center m-5">

  <h3>Créer un nouvel administrateur</h3>

  <%= form_with(model: @admin, local:true, class:"mt-5") do |f| %>

    <form class="mt-5">
      <div class="row mb-4">
        <div class="col">
          <%= f.email_field :email,
              class:"form-control border-300 bg-light",
              autofocus: true,
              placeholder: 'e-mail' 
          %> 
        </div>
      </div>
      <div class="row mb-4">
        <div class="col">
          <%= f.password_field :password,
              class:"form-control border-300 bg-light",
              placeholder: "mot de passe" 
          %> 
        </div>
        <div class="col">
          <%= f.password_field :password_confirmation,
              class:"form-control border-300 bg-light",
              placeholder: "mot de passe"
          %>
        </div>
      </div>  
      <div class="row mb-4 align-items-center">
        <div class="col-auto">
          <%= f.submit :"Ajouter un admin",
              class:"btn btn-dark btn-block mt-3",
              autofocus: true 
          %>                      
        </div>
      </div>
    </form>
<%= link_to "Retour", root_path, class:"btn btn-outline-dark btn-block mt-3" %>            

  <% end %>
</div>
</div>

app/views/admins/show.html.erb
<h1>Admins#show</h1>
<p>Find me in app/views/admins/show.html.erb</p>