config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions", passwords: "admins/passwords", registrations: "admins/registrations"}
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations"}

  resources :workout_programs

  authenticated :user do
    root to: 'users#show', as: :authenticated_user_root
  end

  authenticated :admin do
    root to: 'admins#index', as: :authenticated_admin_root
  end

  unauthenticated do
    root to: 'home#index'
  end

  resources :users do
    resources :profile, only: [:index, :show, :new, :create, :update, :edit]
    collection {get :workout_program}
  end

  namespace :admins do
    resources :users, only: [:index, :new, :create, :update, :edit]
    resources :profile, only: [:index, :new, :create, :update, :edit]
  end

  resources :admins do [:index]
    collection {get :import}
  end

  resources :sports do
    collection {post :import}
  end
  
  resources :home, only: [:index] do
    collection {get :import}
    collection {get :contact}
    collection {get :terms}
    collection {get :team}
  end

  resources :sport_roles, only: [:index] do
    collection {post :import}
  end

  resources :qualities, only: [:index] do
    collection {post :import}
  end

  resources :capacities, only: [:index] do
    collection {post :import}
  end

  resources :muscular_groups, only: [:index] do
    collection {post :import}
  end

  resources :training_methods, only: [:index] do
    collection {post :import}
  end

  resources :exercises, only: [:index] do
    collection {post :import}
  end

  resources :intensities, only: [:index] do
    collection {post :import}
  end

  resources :levels, only: [:index] do
    collection {post :import}
  end

  resources :extypes, only: [:index] do
    collection {post :import}
  end

  resources :muscles, only: [:index] do
    collection {post :import}
  end

  resources :variants, only: [:index] do
    collection {post :import}
  end

  resources :roles_muscular_group_capacities, only: [:index] do
    collection {post :import}
  end

  resources :training_method_exercises, only: [:index] do
    collection {post :import}
  end

  resources :training_method_levels, only: [:index] do
    collection {post :import}
  end

  resources :training_method_intensities, only: [:index] do
    collection {post :import}
  end

  resources :exercise_variants, only: [:index] do
    collection {post :import}
  end

  resources :charges do
    collection {get :success}
    collection {get :new_card}
    collection {post :create_card}
    collection {post :delete_card}
    collection {post :subscribe}
    collection {post :cancel_subscription}
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_confirmation_of :password
  has_one :profile, dependent: :destroy
  has_many :messages, dependent: :destroy

  has_one_attached :avatar
  
  after_create :welcome_send, :profile_creation

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def profile_creation
    puts "hello"
    puts email
    puts User.find_by(email: email).id
    
    p = Profile.new(
      user_id: User.find_by(email: email).id
    )
    p.save(validate: false)
  end
  
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin, only: [:index, :edit]

  def authenticate_admin
    unless current_admin
      flash[:alert] = "Accès non autorisé"
      redirect_to root_path
    end
  end

  def index
    @disable_footer = true
    @users= User.all
    puts "hello"
  end

  def edit
    @disable_footer = true
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(profile_params)
      flash[:alert] = "Le Profil à été mis à jour"
      redirect_to admins_users_path
    else
      flash[:error] = "S'il vous plait, completez tous les champs du formulaire avec le format correct"
      redirect_to request.referrer
    end
  end

  private

  def profile_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  include Accessible
  skip_before_action :check_user, except: [:new, :create]
  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_sign_in_path_for(resource)
    edit_user_profile_path(id: current_user.profile.id, user_id: current_user.id)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  include Accessible
  skip_before_action :check_user, only: :destroy
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:index, :new, :edit, :show]

  def authenticate_user
    unless current_user
      flash[:alert] = "Accès non autorisé"
      redirect_to root_path
    end
  end  

  def show
    @id = current_user.id
    @profile = current_user.profile.id
    @profile_id = current_user.profile.id
    @workout1 = WorkoutProgram.find_by(profile_id: @profile_id)
    @workoutprogram = WorkoutProgram.where(profile_id: @profile_id)
    @exist_program = check_if_exists(@workoutprogram)

    set_meta_tags title: current_user.email,
                  site: 'Argo Athletic',
                  reverse: false,
                  description: 'page utilisateur',
                  keywords: ['user', 'users']
  end

  def check_if_exists(data)
    if data.count > 0
      return true
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
    # show user_avatar
    def user_avatar(user, size=40)
        if user.avatar.attached?
          user.avatar.variant(resize: "#{size}x#{size}!")
        else
          gravatar_image_url(user.email, size: size)
        end
    end
end

app/views/users/show.html.erb
<%= render "layouts/jumbotron" %>

<div class="fancy-tab">

  <div class="nav-bar nav-bar-center">
    <div class="nav-bar-item active"><span class="fas fa-home fs-2"></span><br>Home</div>
    <div class="nav-bar-item"><span class="fas fa-user fs-2"></span><br>Profil</div>
  </div>

  <div class ="tab-contents">
    <div class="tab-content active">

      <div class="container">
      <!-- Two equal columns -->
        <div class="row justify-content-center">
          <div class="col-12 col-sm-12 col-md-10 col-lg-7">
            <div class="d-flex justify-content-center">
              <div class="cardshow col-12 justify-content-center">  
                <%= image_tag 'jump-dash-user.png', class: "rounded-soft img-fluid width: auto", alt: "homme qui saute" %>

                <div class="d3">
                  <div class="titled4 my-2 py-1">VOTRE PROGRAMME</div>
                </div>
                <div class="d-flex justify-content-center">
                  <p class="col-8 text-center">Créer ton programme personnalisé et améliore ta préparation physique</p>
                </div>
                <div class="mb-5">
                  <%if current_user.sub_id.present?%>
                    <% if @exist_program == true %>
                      <div class="d-flex">
                          <%= link_to "voir mon Programme", workout_programs_path, class:"btn btn-danger btn-sm mt-2 btn-block mx-1"%>
                          <%= link_to "Suprimer  Programme", workout_program_path(@workoutprogram.ids), method: 'delete', data: { confirm: "Etes-vous sur de vouloir supprimer votre programme ?" }, class:"btn btn-dark btn-sm mt-2 btn-block mx-1"%>
                      </div>
                    <% else %>
                        <%if current_user.profile.sport_role.nil? && current_user.profile.level.nil? %>
                            <%= link_to "Créer mon Programme", edit_user_profile_path(id: @profile, user_id: @id),autofocus:"true", class:"btn btn-danger btn-sm btn-block"%>
                        <%else%>
                          <%= link_to "Créer mon Programme", new_workout_program_path, autofocus:"true", class:"btn btn-danger btn-sm btn-block py-1 btn-block"%>
                        <%end%>

                    <%end%>
                    
                  <%else%>
                      <%= link_to "S'abonner pour créer mon programmme", success_charges_path, autofocus:"true", class:"btn btn-danger btn-sm"%>
                  <%end%>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
              
    </div>

    
                  
		<div class="tab-content">

      <div class="container">
        <!-- Two equal columns -->
        <div class="row justify-content-center mb-3">

          <div class="col-12 col-md-6 col-lg-5 mb-3">
            <div class="card h-100">

              <div class="d3">
                <p class="titled3 text-center text-md-left ml-3">PROFILE SPORT</p>
              </div>

              <div class="card-body text-center text-md-left">
                <p>Sport :
                <%unless current_user.profile.sport.nil?%>
                <%=current_user.profile.sport.humanize %>
                <%else%>
                <span class="font-italic"><%= link_to "Renseigner votre profil", edit_user_profile_path(id: @profile, user_id: @id)%>
                </span>
                <%end%>
                </p>

                <p>Poste :
                <%unless current_user.profile.sport_role.nil?%>
                <%=current_user.profile.sport_role.humanize %>
                <%else%>
                <span class="font-italic"><%= link_to "Renseigner votre profil", edit_user_profile_path(id: @profile, user_id: @id)%>
                </span>
                <%end%>
                </p>


                <p>Taille :
                <%unless current_user.profile.height.nil?%>
                <%=current_user.profile.height%> cm
                <%else%>
                <span class="font-italic"><%= link_to "Renseigner votre profil", edit_user_profile_path(id: @profile, user_id: @id)%>
                </span>
                <%end%>
                </p>

                <p>Poids :
                <%unless current_user.profile.weight.nil?%>
                <%=current_user.profile.weight%> kg
                <%else%>
                <span class="font-italic"><%= link_to "Renseigner votre profil", edit_user_profile_path(id: @profile, user_id: @id)%>
                </span>
                <%end%>
                </p>

                <p>Niveau :
                <%unless current_user.profile.level.nil?%>
                <%=current_user.profile.level.humanize %>
                <%else%>
                <span class="font-italic"><%= link_to "Renseigner votre profil", edit_user_profile_path(id: @profile, user_id: @id)%>
                  </span>
                <%end%>
                </p>
              </div>
              <%# End Card %>

            </div>
          </div>

          <div class="col-12 col-md-6 col-lg-5 mb-3">
            <div class="card h-100">

              <div class="d3">
                <p class="titled3 text-center">COMPTE UTILISATEUR</p>
              </div>

              <div class="card-body text-center">
                <p>Email : <%=current_user.email%></p>
                <p>Inscription : <%=current_user.created_at.to_date%>
                <p>Abonnement : 
                <%if current_user.sub_id.present?%>
                  Oui
                  <p>Date de souscription :
                  <%= customer_subscription_time%>
                  </p>
                <%else%>
                  Non
                <%end%>
                <br>
                <br>
              </div>

            </div>
          </div>

        </div>

        <div class="row">
          <div class="col-12 col-md-4 mb-3">
            <div class="card h-100">
              <div class="d3">
                <p class="titled3 text-center">EDITER PROFIL SPORT</p>
              </div>

              <div class="card-body text-center">
                <%= link_to "Modifier son profil sport", edit_user_profile_path(id: @profile, user_id: @id), class:"btn btn-danger btn-sm"%>
              </div>
            </div>
          </div>

          <div class="col-12 col-md-4 mb-3">
            <div class="card h-100">
              <div class="d3">
                <p class="titled3 text-center">EDITER COMPTE UTILISATEUR</p>
              </div>

              <div class="card-body text-center">
                <%= link_to "Modifier son compte utilisateur", edit_user_registration_path, class:"btn btn-danger btn-sm"%>
              </div>
            </div>
          </div>

          <div class="col-12 col-md-4 mb-3">
            <div class="card h-100">
              <div class="d3">
                <p class="titled3 text-center">DECONNEXION</p>
              </div>

              <div class="card-body text-center">
                <%= link_to "Déconnexion", destroy_admin_session_path, method: 'delete', class:"btn btn-danger btn-sm"%>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>
	</div>
</div>